#!/usr/bin/env bash
# Throwaway spike tooling (Phase 0). Generates/removes dummy "recent" skills of
# three payload shapes (naive / proxy / merged) to measure resident skill context
# cost against Claude Code 2.1.211 (bug anthropics/claude-code#14882). SAFETY: every
# write and delete is gated to the exact `spike-dummy-` prefix. Real skills are never
# touched; the skills root is never removed.
set -euo pipefail

SKILLS_DIR="$HOME/.claude/skills"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BRIEF_FILE="$SCRIPT_DIR/recent-brief.md"
PREFIX="spike-dummy-"
MARKER=".spike-generated"

die() { echo "gen-skills: $*" >&2; exit 1; }

# Remove one dummy dir, refusing anything outside our namespace or lacking our marker.
remove_dummy_dir() {
  local d="$1"
  [ -e "$d" ] || return 0
  case "$d" in
    "$SKILLS_DIR/$PREFIX"*) ;;
    *) die "refusing to remove '$d' (outside $PREFIX namespace)";;
  esac
  [ -f "$d/$MARKER" ] || die "collision: '$d' exists but was not generated by this tool (missing $MARKER) — aborting to protect real skills"
  rm -rf "$d"
}

# Clean every dummy dir of a given shape (idempotency helper).
clean_shape() {
  local shape="$1" d
  for d in "$SKILLS_DIR/$PREFIX$shape-"*/; do
    [ -e "$d" ] || continue
    remove_dummy_dir "${d%/}"
  done
}

# Repeat/pad prose to a target char length, then hard-truncate.
padded() {
  local target="$1" seed="$2" out=""
  while [ "${#out}" -lt "$target" ]; do out="$out$seed"; done
  printf '%s' "${out:0:$target}"
}

make_naive() {
  local i pad body dir
  i="$1"
  dir="$SKILLS_DIR/${PREFIX}naive-$i"
  mkdir -p "$dir"
  : > "$dir/$MARKER"
  # ~1000-char description (near the 1024 cap, never over). No angle brackets.
  pad="$(padded 1000 "Project memory brief number $i: consolidated recent memory for a real project — records the active architecture decisions, current work streams, open questions to keep in working context, established conventions from prior sessions, durable knowledge and common methods, plus pointers to deeper long-term memory that pages in on demand. Recall this brief when resuming work so the agent reboots its identity and reassembles the right context without drowning in irrelevant history. ")"
  body="$(padded 3000 "## Session log $i

Consolidated recent memory body for project $i. This section stands in for the few-KB full memory a real project-memory skill would carry: decisions made, files touched, commands run, and the reasoning behind each. It is load-on-demand under progressive disclosure, so it should not count toward always-on catalog cost.

- Decision: keep the index structured, never prose.
- Decision: access-time drives the lifecycle, not creation-time.
- Open question: does the body load at startup on this CC version?

")"
  {
    printf -- '---\n'
    printf 'name: %snaive-%s\n' "$PREFIX" "$i"
    printf 'description: %s\n' "$pad"
    printf -- '---\n\n'
    printf '%s\n' "$body"
  } > "$dir/SKILL.md"
}

make_proxy() {
  local i desc dir
  i="$1"
  dir="$SKILLS_DIR/${PREFIX}proxy-$i"
  mkdir -p "$dir"
  : > "$dir/$MARKER"
  # Lean (~150 char) description; frontmatter keeps the skill out of the model's way.
  desc="$(padded 150 "Proxy brief $i: lean pointer to the real project memory file; body just reads the memory on demand. ")"
  {
    printf -- '---\n'
    printf 'name: %sproxy-%s\n' "$PREFIX" "$i"
    printf 'description: %s\n' "$desc"
    printf 'disable-model-invocation: true\n'
    printf 'user-invocable: true\n'
    printf -- '---\n\n'
    printf 'Read @~/.claude/memory/project-%s/long-term-memory.md\n' "$i"
  } > "$dir/SKILL.md"
}

gen_skills() {
  local shape="$1" n="$2" i idx
  [[ "$n" =~ ^[0-9]+$ ]] || die "N must be a non-negative integer"
  clean_shape "$shape"
  for ((i=1; i<=n; i++)); do
    idx="$(printf '%04d' "$i")"
    "make_$shape" "$idx"
  done
  echo "gen-skills: installed $n ${PREFIX}${shape}-* skill(s)"
}

gen_merged() {
  local n="$1" i idx
  [[ "$n" =~ ^[0-9]+$ ]] || die "N must be a non-negative integer"
  : > "$BRIEF_FILE"
  for ((i=1; i<=n; i++)); do
    idx="$(printf '%04d' "$i")"
    padded 150 "Brief $idx: recent project memory one-liner — decisions, work streams, and a hook so the agent can match and reheat the deeper long-term memory by id. " >> "$BRIEF_FILE"
    printf '\n' >> "$BRIEF_FILE"
  done
  echo "gen-skills: wrote merged brief with $n entry/entries to $BRIEF_FILE (no skills installed)"
}

clean_all() {
  local d
  for d in "$SKILLS_DIR/$PREFIX"*/; do
    [ -e "$d" ] || continue
    remove_dummy_dir "${d%/}"
  done
  [ -f "$BRIEF_FILE" ] && rm -f "$BRIEF_FILE"
  echo "gen-skills: cleaned all ${PREFIX}* skills and merged brief"
}

usage() { die "usage: gen-skills.sh {naive|proxy|merged} N | --clean"; }

[ -d "$SKILLS_DIR" ] || die "skills dir not found: $SKILLS_DIR"

case "${1:-}" in
  naive|proxy) [ $# -eq 2 ] || usage; gen_skills "$1" "$2";;
  merged)      [ $# -eq 2 ] || usage; gen_merged "$2";;
  --clean)     clean_all;;
  *)           usage;;
esac
